spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.21.137.17:3306/spring_boot_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: mengwei131575585
  redis:
    host: 172.21.137.17
    database: 1
    port: 6379
    password: mengwei131575585
    timeout: 10000ms
    lettuce:
      pool:
        enabled: true
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 180000
  ldap:
    urls: ldap://172.21.137.17:389
    base: dc=example,dc=org
    username: cn=Manager,dc=example,dc=org
    password: mengwei131575585
  kafka:
    bootstrap-servers: 172.21.137.17:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: spring_boot_demo_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer