server:
  port: 8090

spring:
  application:
    name: spring-boot-demo
  profiles:
    active: local
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

log:
  file:
    name: spring-boot-demo.log
    path: logs

skip-urls: /swagger-ui/**,/swagger-ui.html,/swagger-resources/**,/v2/api-docs,/v3/api-docs,/login,/login/image/captcha,/token/refresh